spring.application.name=asn

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/asn_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=asnGlobalProjectManagementSystemSecretKey2026BrycenCambodia
app.jwt.expiration=86400000
# 86400000 ms = 24 hours

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Server Port
server.port=8080

#translation.provider=mock
translation.provider=deepl
translation.deepl.api-key=5c732ab0-ba9a-4259-9bb7-6f27f31425a5:fx

# spring.application.name=demo

# spring.datasource.url=jdbc:mysql://localhost:3306/asn_db
# spring.datasource.username=root
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

