spring.application.name=asn

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.web.resources.static-locations=file:uploads/,classpath:/static/
spring.mvc.static-path-pattern=/uploads/**

# Server Port
server.port=8080

# Translation
translation.provider=${TRANSLATION_PROVIDER}
translation.deepl.api-key=${DEEPL_API_KEY}

# Claude AI
anthropic.api.key=${ANTHROPIC_API_KEY}